<?php

namespace ContainerPt8fRXN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_0OeC8FnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.0OeC8Fn' shared service.
     *
     * @return \App\Repository\RandomNumberRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ShopController::index()": the $randomNumberRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RandomNumberRepository".');
    }
}
