<?php

namespace ContainerPt8fRXN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JAXISS0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JAXISS0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JAXISS0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'randomNumberRepository' => ['privates', '.errored.0OeC8Fn', NULL, 'Cannot determine controller argument for "App\\Controller\\ShopController::index()": the $randomNumberRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RandomNumberRepository".'],
        ], [
            'manager' => '?',
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'randomNumberRepository' => '?',
        ]);
    }
}
