<?php

namespace ContainerC5puA3I;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R77E5wlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R77E5wl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R77E5wl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.R77E5wl.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.R77E5wl": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'manager' => '?',
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
