home:
  path: /
  controller: App\Controller\HomeController::index

shop:
  path: /randomQuestion
  controller: App\Controller\ShopController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
  path: /logout

register:
  path: /register
  controller: App\Controller\RegistrationController.php

admin:
  path: /admin
  controller: App\Controller\Admin\AdminPropertyController::index

merci:
  path: /merci
  controller: App\Controller\MerciController::index
  
  