<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCsiaGWa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCsiaGWa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCsiaGWa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCsiaGWa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCsiaGWa\App_KernelDevDebugContainer([
    'container.build_hash' => 'CsiaGWa',
    'container.build_id' => '11d7ad75',
    'container.build_time' => 1665678596,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCsiaGWa');
