<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD6AlTxi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD6AlTxi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD6AlTxi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD6AlTxi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD6AlTxi\App_KernelDevDebugContainer([
    'container.build_hash' => 'D6AlTxi',
    'container.build_id' => '5a14075c',
    'container.build_time' => 1665653354,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD6AlTxi');
